workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

      - name: Install Dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Build Web App
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build

      - name: Sync Capacitor (SPM Mode)
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          # Fetch the clean files from Apple
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # We still run this to set basic settings, but we won't rely on it 100%
          xcode-project use-profiles --project "ios/App/App.xcodeproj"

      - name: Build IPA (Force Profile)
        script: |
          # 1. Find the profile we just downloaded
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          
          if [ -z "$PROFILE_PATH" ]; then
            echo "❌ ERROR: No provisioning profile found!"
            exit 1
          fi
          
          echo "✅ Found profile at: $PROFILE_PATH"

          # 2. Extract the UUID from the profile
          UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          echo "✅ Using Profile UUID: $UUID"

          # 3. Build using the UUID directly (Bypassing project settings)
          xcode-project build-ipa             --project "ios/App/App.xcodeproj"             --scheme "App"             --archive-flags "PROVISIONING_PROFILE_SPECIFIER=$UUID CODE_SIGN_STYLE=Manual"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
