workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        TEAM_ID: "X53LJ84526"
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install dependencies and build web app
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun install
          bun run build
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App && pod install
          else
            echo "No Podfile found, skipping pod install"
          fi
      - name: Set up code signing
        script: |
          # Initialize keychain for code signing
          keychain initialize
          
          # Fetch signing files from Codemagic
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          
          # Add certificates to keychain
          keychain add-certificates
          
          # Set up code signing settings
          xcode-project use-profiles
      - name: Build IPA
        script: |
          # Build archive
          if [ -d "ios/App/App.xcworkspace" ]; then
            xcodebuild archive \
              -workspace ios/App/App.xcworkspace \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath build/ios/App.xcarchive
          else
            xcodebuild archive \
              -project "$XCODE_PROJECT" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath build/ios/App.xcarchive
          fi
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/ios/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ~/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
