workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: 1. Install Tools & Build Web App
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun install
          bun run build
          npx cap sync ios

      - name: 2. Force Bundle ID & Download Keys
        script: |
          # A. Force the Project to match our Bundle ID
          echo "🔹 Setting Bundle ID to $BUNDLE_ID..."
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" $XCODE_PROJECT/project.pbxproj
          
          # B. Initialize Keychain
          keychain initialize
          
          # C. Fetch files (Create new ones if missing)
          echo "🔹 Fetching signing files..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # D. Add to Keychain
          keychain add-certificates
          
          # E. DEBUG: List the folder to verify download
          echo "🔹 Checking Profile Folder:"
          ls -R ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "❌ Folder not found!"

      - name: 3. Build IPA (Force Feed UUID)
        script: |
          # A. Find the profile (taking the first one found)
          # We search recursively in case it's in a subfolder
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          
          # Safety Check: Did we find it?
          if [ -z "$PROFILE_PATH" ]; then
            echo "❌ ERROR: No profile found! 'fetch-signing-files' failed to save the file."
            exit 1
          fi
          
          echo "✅ Found profile at: $PROFILE_PATH"

          # B. Extract UUID
          UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          echo "✅ UUID: $UUID"

          # C. Build with Force Feed
          xcode-project build-ipa             --project "$XCODE_PROJECT"             --scheme "$XCODE_SCHEME"             --archive-flags "CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=$UUID"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
