workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        CODE_SIGN_STYLE: "Automatic"
        TEAM_ID: "X53LJ84526"
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install dependencies and build web app
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun install
          bun run build
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App && pod install
          else
            echo "No Podfile found, skipping pod install"
          fi
      - name: Build IPA
        script: |
          # Create export options plist
          cat > /Users/builder/export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          
          # Build archive
          if [ -d "ios/App/App.xcworkspace" ]; then
            xcodebuild archive \
              -workspace ios/App/App.xcworkspace \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath build/ios/App.xcarchive \
              CODE_SIGN_STYLE=Automatic \
              DEVELOPMENT_TEAM=$TEAM_ID
          else
            xcodebuild archive \
              -project "$XCODE_PROJECT" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath build/ios/App.xcarchive \
              CODE_SIGN_STYLE=Automatic \
              DEVELOPMENT_TEAM=$TEAM_ID
          fi
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/ios/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
