workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

      - name: Install Dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Build Web App
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build

      - name: Sync iOS & Install Pods
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync ios
          
          # DEBUG: List all files so we can see what is happening
          echo "--- FILE STRUCTURE DEBUG ---"
          ls -R ios
          echo "----------------------------"

          # SMART FIX: Find the Podfile wherever it is
          PODFILE_PATH=$(find ios -name Podfile | head -n 1)
          
          if [ -z "$PODFILE_PATH" ]; then
            echo "❌ CRITICAL ERROR: Podfile is missing from the Git repo!"
            exit 1
          else
            echo "✅ Found Podfile at: $PODFILE_PATH"
            cd $(dirname "$PODFILE_PATH")
            pod install --repo-update
          fi

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          # We search for the workspace similarly to avoid path errors
          WORKSPACE_PATH=$(find ios -name "*.xcworkspace" | head -n 1)
          xcode-project build-ipa --workspace "$WORKSPACE_PATH" --scheme "App"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
