workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

      - name: Install Dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Build Web App
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build

      - name: Sync Capacitor (SPM Mode)
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          # Just sync the files, no Pod install needed
          npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          # FIX: Build the .xcodeproj file directly (since you have no workspace)
          xcode-project build-ipa --project "ios/App/App.xcodeproj" --scheme "App"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
