workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

      - name: Install Dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Build Web App
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build

      - name: Sync Capacitor (SPM Mode)
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          # Fetch the files from Apple (Since your account is clean, this creates NEW valid ones)
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # FORCE FIX 1: Update the Bundle ID in the project file
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" ios/App/App.xcodeproj/project.pbxproj
          
          # FORCE FIX 2: Set Manual Signing in the project file
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' ios/App/App.xcodeproj/project.pbxproj

          # DEBUG: Check if the ID was actually changed
          echo "--- CHECKING BUNDLE ID ---"
          grep "PRODUCT_BUNDLE_IDENTIFIER" ios/App/App.xcodeproj/project.pbxproj | head -n 1
          echo "----------------------------"
          
          # Apply the profiles to the project
          xcode-project use-profiles --project "ios/App/App.xcodeproj"

      - name: Build IPA
        script: |
          # FORCE FIX 3: Pass "Manual" style directly to the build command
          xcode-project build-ipa             --project "ios/App/App.xcodeproj"             --scheme "App"             --archive-flags "CODE_SIGN_STYLE=Manual"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
