workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: 1. Install Tools & Build Web App
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun install
          bun run build
          npx cap sync ios

      - name: 2. Fetch Signing Files
        script: |
          # A. Force Project to match Bundle ID
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" $XCODE_PROJECT/project.pbxproj
          
          # B. Initialize Keychain
          keychain initialize
          
          # C. Fetch keys (Standard command)
          echo "🔹 Fetching signing files from Apple..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # D. Add to Keychain
          keychain add-certificates

      - name: 3. Build IPA (Deep Search Search)
        script: |
          # A. DEEP SEARCH: Look everywhere for the downloaded profile
          echo "🔹 Searching for profile..."
          PROFILE_PATH=$(find $HOME -name "*.mobileprovision" -print -quit)
          
          if [ -z "$PROFILE_PATH" ]; then
            echo "❌ ERROR: No profile found on the entire machine."
            echo "This usually means the Apple API Key doesn't have 'Certificate Access'."
            exit 1
          fi
          
          echo "✅ Found profile at: $PROFILE_PATH"

          # B. Extract UUID
          UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          echo "✅ UUID: $UUID"

          # C. Build
          xcode-project build-ipa             --project "$XCODE_PROJECT"             --scheme "$XCODE_SCHEME"             --archive-flags "CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=$UUID"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
