workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.arzmadeit.blatt"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install Bun & Dependencies
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun install

      - name: Build Web App & Sync
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build
          npx cap sync ios

      - name: 🧹 Sanitize Xcode Project (The Fix)
        script: |
          # This is the "Nuclear" step. It removes conflicting settings from your project file.
          echo "Removing old signing settings..."
          project_file="ios/App/App.xcodeproj/project.pbxproj"
          
          # Remove "Automatic" signing style
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' $project_file
          
          # Remove any hardcoded Development Team IDs from your personal machine
          sed -i '' '/DEVELOPMENT_TEAM =/d' $project_file
          
          # Remove any hardcoded Provisioning Profiles
          sed -i '' '/PROVISIONING_PROFILE_SPECIFIER =/d' $project_file
          
          echo "✅ Project file sanitized."

      - name: Set up code signing
        script: |
          keychain initialize
          
          # Fetch fresh certificates from Apple
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # Apply the new profile to the CLEAN project file
          xcode-project use-profiles --project "ios/App/App.xcodeproj"

      - name: Build IPA
        script: |
          # Build with strictly Manual signing
          xcode-project build-ipa             --project "ios/App/App.xcodeproj"             --scheme "App"             --archive-flags "CODE_SIGN_STYLE=Manual"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
